name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.2.0

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: |
	    mkdir -p ${HOME}/.config/universal-server/
	    cd ${HOME}/.config/universal-server/ && ln -s $(pwd)/priv/for-testing/us.config
	    make test NODE_NAMING="--sn"
